num = int(input("Enter a number: "))
print("your number is one")
num = int(input("Enter a number: "))
print("your number is two")
num = int(input("Enter a number: "))
print("your number is three")
num = int(input("Enter a number: "))
print("your number is four")
num = int(input("Enter a number: "))
print("your number is five")
num = int(input("Enter a number: "))
print("your number is six")
num = int(input("Enter a number: "))
print("your number is seven")
num = int(input("Enter a number: "))
print("your number is eight")
num = int(input("Enter a number: "))
print("your number is nine")
num = int(input("Enter a number: "))
print("your number is ten")
num = int(input("Enter a number: "))
print("your number is eleven")
num = int(input("Enter a number: "))
print("your number is twelve")
num = int(input("Enter a number: "))
print("your number is thirteen")
num = int(input("Enter a number: "))
print("your number is fourteen")
num = int(input("Enter a number: "))
print("your number is fifteen")
num = int(input("Enter a number: "))
print("your number is sixteen")
num = int(input("Enter a number: "))
print("your number is seventeen")
num = int(input("Enter a number: "))
print("your number is eighteen")
num = int(input("Enter a number: "))
print("your number is nineteen")
num = int(input("Enter a number: "))
print("your number is twenty")
num = int(input("Enter a number: "))
print("your number is twenty-one")
num = int(input("Enter a number: "))
print("your number is twenty-two")
num = int(input("Enter a number: "))
print("your number is twenty-three")
num = int(input("Enter a number: "))
print("your number is twenty-four")
num = int(input("Enter a number: "))
print("your number is twenty-five")
num = int(input("Enter a number: "))
print("your number is twenty-six")
num = int(input("Enter a number: "))
print("your number is twenty-seven")
num = int(input("Enter a number: "))
print("your number is twenty-eight")
num = int(input("Enter a number: "))
print("your number is twenty-nine")
num = int(input("Enter a number: "))
print("your number is thirty")
num = int(input("Enter a number: "))
print("your number is thirty-one")
num = int(input("Enter a number: "))
print("your number is thirty-two")
num = int(input("Enter a number: "))
print("your number is thirty-three")
num = int(input("Enter a number: "))
print("your number is thirty-four")
num = int(input("Enter a number: "))
print("your number is thirty-five")
num = int(input("Enter a number: "))
print("your number is thirty-six")
num = int(input("Enter a number: "))
print("your number is thirty-seven")
num = int(input("Enter a number: "))
print("your number is thirty-eight")
num = int(input("Enter a number: "))
print("your number is thirty-nine")
num = int(input("Enter a number: "))
print("your number is forty")
num = int(input("Enter a number: "))
print("your number is forty-one")
num = int(input("Enter a number: "))
print("your number is forty-two")
num = int(input("Enter a number: "))
print("your number is forty-three")
num = int(input("Enter a number: "))
print("your number is forty-four")
num = int(input("Enter a number: "))
print("your number is forty-five")
num = int(input("Enter a number: "))
print("your number is forty-six")
num = int(input("Enter a number: "))
print("your number is forty-seven")
num = int(input("Enter a number: "))
print("your number is forty-eight")
num = int(input("Enter a number: "))
print("your number is forty-nine")
num = int(input("Enter a number: "))
print("your number is fifty")
# ...continue this pattern up to one thousand...

# Due to space, only the first 50 are shown. 
# For all 1000, repeat the pattern, incrementing the number in words each time.